### ISSUE TITLE
Version 1.0.1-pre01: Could not find a part of the path 'C:\Projects\Clients\AirProducts\src\CodeGen.Conventions.config'.

### ISSUE THREAD

**Issue by jeroendatema** [blipson89/Leprechaun#15]
If I run 1.0.1-pre01 I get this error:
`Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Projects\Clients\AirProducts\src\CodeGen.Conventions.config'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Threading.CompressedStack.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at Leprechaun.Console.Program.BuildConfiguration(ConsoleArgs args)
   at Leprechaun.Console.Program.Main(String[] args)`

If I switch back to 1.0.0 it works fine.

**Comment by blipson89** [comment]
It looks like there was a glitch with the package generation. I've fixed it going forward so this won't happen again. 

I've updated the zip file in the release. If you re-download it should be fine. Thanks for the heads-up!
