### ISSUE TITLE
NuGet Package Doesn't Have Needed Dependencies?

### ISSUE THREAD

**Issue by DavidMtbg** [blipson89/Leprechaun#17]
I'm running Leprechaun from a Gulp script (although I tried from command line with the same result) and receive the following error.  If I copy all of the DLLs from the zip on GitHub it works fine, but that shouldn't be necessary for a NuGet package.

Here is the error text:
`C:\Users\david\Source\Repos\Website> cmd.exe /c gulp -b "C:\Users\david\Source\Repos\Website" --color --gulpfile "C:\Users\david\Source\Repos\Website\Gulpfile.js" 07-Code-Generate-Models
[15:52:55] Using gulpfile ~\Source\Repos\Website\Gulpfile.js
[15:52:55] Starting '07-Code-Generate-Models'...
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'CommandLineArgumentsParser, Version=3.0.9.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Leprechaun.Console.Program.Main(String[] args)
[15:52:55] '07-Code-Generate-Models' errored after 164 ms
[15:52:55] Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c ".\packages\Leprechaun.Console.1.0.1-pre01\lib\net46\Leprechaun.console.exe /c .\src\Foundation\CodeGen\code\Leprechaun.config"
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'CommandLineArgumentsParser, Version=3.0.9.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Leprechaun.Console.Program.Main(String[] args)
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
Process terminated with code 1.`

Thanks!

**Comment by blipson89** [comment]
Hi @DavidMtbg,

You want to use the package [Leprechaun.Console.Runner](https://www.nuget.org/packages/Leprechaun.Console.Runner). Try switching to that one and let me know if that fixes the issue?

Thanks,
-Ben

**Comment by DavidMtbg** [comment]
Thanks, Ben! That includes the dependencies in the package along with the executable.  I guess I used the other one because the [ReadMe](https://github.com/blipson89/Leprechaun/blob/master/README.md) pointed to it.

The runner package doesn't seem to contain the Scripts.  Would I install a different NuGet package for that? I had them in the project before, but when I uninstalled the other Leprechaun packages to clean things up before installing Leprechaun.Console.Runner, they were removed and not installed with Runner.

Thanks again!
David

**Comment by blipson89** [comment]
Hmmm I'll have to get back to you on that one. I think I need to rework these NuGet packages. They were setup a while ago and things have evolved a bit and there may be room for consolidation.
